name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GIT_USERNAME }}/den-store-f-rjulsoppgaven_yff_elias:latest .
          docker run --rm -e GIT_USERNAME=${{ secrets.GIT_USERNAME }} -e GIT_TOKEN=${{ secrets.GIT_TOKEN }} -v ${{ github.workspace }}/build:/app/build ghcr.io/${{ github.repository_owner }}/den-store-f-rjulsoppgaven_yff_elias:latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build