name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Docker image
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg GIT_USERNAME=${{ secrets.GIT_USERNAME }} --build-arg GIT_TOKEN=${{ secrets.GIT_TOKEN }} -t ghcr.io/${REPO_OWNER_LOWER}/den-store-f-rjulsoppgaven-yff-elias:latest .
          mkdir -p ${{ github.workspace }}/build
          echo "Contents of build directory before running Docker container:"
          ls -la ${{ github.workspace }}/build
          docker run --rm -e GIT_USERNAME=${{ secrets.GIT_USERNAME }} -e GIT_TOKEN=${{ secrets.GIT_TOKEN }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -v ${{ github.workspace }}/build:/app/build ghcr.io/${REPO_OWNER_LOWER}/den-store-f-rjulsoppgaven-yff-elias:latest
          echo "Contents of build directory after running Docker container:"
          ls -la ${{ github.workspace }}/build

      - name: List contents of build directory before deployment
        run: ls -la ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github

      - name: List contents of gh-pages branch before deployment
        run: |
          rm -rf gh-pages
          git clone --branch gh-pages https://github.com/${{ github.repository_owner }}/Den-store-f-rjulsoppgaven_YFF-Elias.git gh-pages
          echo "Contents of gh-pages branch before deployment:"
          ls -la gh-pages

      - name: List contents of gh-pages branch after deployment
        run: |
          rm -rf gh-pages
          git clone --branch gh-pages https://github.com/${{ github.repository_owner }}/Den-store-f-rjulsoppgaven_YFF-Elias.git gh-pages
          echo "Contents of gh-pages branch after deployment:"
          ls -la gh-pages